### ISSUE TITLE
[Bug] build from source error, follow the instructions but cannot find mpi-cxx

### ISSUE THREAD

**Issue by ehuaa** [InternLM/lmdeploy#584] opened 2023-10-19 03:33 UTC
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

When I followed the procedure of installation from source, I came across this  error, can you have a look at and help me fix this error, Thanks   In conda install command I found openmpi-mpicxx will be installed, is there something wrong my openmpi-cxx is not successfully installed, how can i check this?

CMake Error at /usr/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find MPI (missing: MPI_CXX_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.24/Modules/FindMPI.cmake:1835 (find_package_handle_standard_args)
  CMakeLists.txt:68 (find_package)

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    binutils_impl_linux-64-2.38|       h2a08ee3_1         5.2 MB
    binutils_linux-64-2.38.0   |       hc2dff05_0          24 KB
    ca-certificates-2023.7.22  |       hbcca054_0         146 KB  conda-forge
    cudatoolkit-10.2.89        |      h713d32c_10       449.7 MB  conda-forge
    gcc_impl_linux-64-11.2.0   |       h1234567_1        22.2 MB
    gcc_linux-64-11.2.0        |       h5c386dc_0          25 KB
    gxx_impl_linux-64-11.2.0   |       h1234567_1        10.6 MB
    gxx_linux-64-11.2.0        |       hc2dff05_0          24 KB
    kernel-headers_linux-64-2.6.32|      he073ed8_16         692 KB  conda-forge
    libgcc-devel_linux-64-11.2.0|       h1234567_1         2.5 MB
    libgfortran-ng-7.5.0       |      h14aa051_20          23 KB  conda-forge
    libgfortran4-7.5.0         |      h14aa051_20         1.2 MB  conda-forge
    libstdcxx-devel_linux-64-11.2.0|       h1234567_1        14.6 MB
    mpi-1.0                    |          openmpi           4 KB  conda-forge
    nccl-2.14.3.1              |       h1a5f58c_0       106.4 MB  conda-forge
    openmpi-3.1.3              |    h1c2f66e_1001         4.0 MB  conda-forge
    openmpi-mpicxx-3.1.3       |    h6bb024c_1001           7 KB  conda-forge
    rapidjson-1.1.0            |    he1b5a44_1002         104 KB  conda-forge
    sysroot_linux-64-2.12      |      he073ed8_16        14.6 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       632.1 MB

The following NEW packages will be INSTALLED:

  binutils_impl_lin~ pkgs/main/linux-64::binutils_impl_linux-64-2.38-h2a08ee3_1 
  binutils_linux-64  pkgs/main/linux-64::binutils_linux-64-2.38.0-hc2dff05_0 
  cudatoolkit        conda-forge/linux-64::cudatoolkit-10.2.89-h713d32c_10 
  gcc_impl_linux-64  pkgs/main/linux-64::gcc_impl_linux-64-11.2.0-h1234567_1 
  gcc_linux-64       pkgs/main/linux-64::gcc_linux-64-11.2.0-h5c386dc_0 
  gxx_impl_linux-64  pkgs/main/linux-64::gxx_impl_linux-64-11.2.0-h1234567_1 
  gxx_linux-64       pkgs/main/linux-64::gxx_linux-64-11.2.0-hc2dff05_0 
  kernel-headers_li~ conda-forge/noarch::kernel-headers_linux-64-2.6.32-he073ed8_16 
  libgcc-devel_linu~ pkgs/main/linux-64::libgcc-devel_linux-64-11.2.0-h1234567_1 
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.5.0-h14aa051_20 
  libgfortran4       conda-forge/linux-64::libgfortran4-7.5.0-h14aa051_20 
  libstdcxx-devel_l~ pkgs/main/linux-64::libstdcxx-devel_linux-64-11.2.0-h1234567_1 
  mpi                conda-forge/linux-64::mpi-1.0-openmpi 
  nccl               conda-forge/linux-64::nccl-2.14.3.1-h1a5f58c_0 
  **openmpi            conda-forge/linux-64::openmpi-3.1.3-h1c2f66e_1001 
  openmpi-mpicxx     conda-forge/linux-64::openmpi-mpicxx-3.1.3-h6bb024c_1001** 
  rapidjson          conda-forge/linux-64::rapidjson-1.1.0-he1b5a44_1002 
  sysroot_linux-64   conda-forge/noarch::sysroot_linux-64-2.12-he073ed8_16 

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    pkgs/main::ca-certificates-2023.08.22~ --> conda-forge::ca-certificates-2023.7.22-hbcca054_0 

Proceed ([y]/n)? y

Downloading and Extracting Packages
                                                                                                                                     
Preparing transaction: done                                                                                                          
Verifying transaction: done                                                                                                          
Executing transaction: / By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html                                                        
                                                                                                                                     
done                                                                       

### Reproduction

[Build from source](https://github.com/InternLM/lmdeploy/blob/main/docs/en/build.md#build-from-source)
install packages for compiling and running:

conda create -n lmdeploy python=3.10
conda activate lmdeploy

git clone https://github.com/InternLM/lmdeploy.git
cd lmdeploy

pip install -r requirements.txt
conda install openmpi-mpicxx nccl rapidjson -c conda-forge
build and install lmdeploy:

mkdir build && cd build
sh ../generate.sh

After running generate.sh command above, i got this error

**Comment by RunningLeon** [comment] 2023-10-19 03:48
@ehuaa hi, could you try with the prebuilt docker image: `docker pull openmmlab/lmdeploy:latest`. https://hub.docker.com/r/openmmlab/lmdeploy/tags

**Comment by pppppM** [comment] 2023-10-19 03:52
@ehuaa This issue may be caused by PR #370 

The installation method of conda may not be very robust, you can try the earliest compilation and installation method of lmdeploy

https://github.com/InternLM/lmdeploy/blob/18c386d914e8c7ec35b8be1d146a579a45deacad/docs/en/build.md

**Comment by ehuaa** [comment] 2023-10-19 05:06
![image](https://github.com/InternLM/lmdeploy/assets/5137359/af8e615f-034c-43ab-8298-540da55d522d)

**Comment by ehuaa** [comment] 2023-10-19 05:08
I have checked my installation of mpicxx and found it in lmdeploy/bin/mpicxx  which has been successfully installed. I wonder if the CMakeLists.txt has something wrong with mpicxx?

**Comment by ehuaa** [comment] 2023-10-19 05:10
@pppppM 
![image](https://github.com/InternLM/lmdeploy/assets/5137359/4d019b42-1e4c-4480-a8e0-637c32260d3b)
![image](https://github.com/InternLM/lmdeploy/assets/5137359/602bc46b-72da-4333-9d2b-4ec2c63d864d)
![image](https://github.com/InternLM/lmdeploy/assets/5137359/b4ba76da-262d-4100-afe4-090e881de3b6)
maybe you should add FindMPICXX here?

**Comment by ehuaa** [comment] 2023-10-19 05:36
> @ehuaa This issue may be caused by PR #370
> 
> The installation method of conda may not be very robust, you can try the earliest compilation and installation method of lmdeploy
> 
> https://github.com/InternLM/lmdeploy/blob/18c386d914e8c7ec35b8be1d146a579a45deacad/docs/en/build.md

@pppppM I tried this earlier version of installation method  and install mpi from source just can't work well... can you take a look at the MPI env above ? I think this can make installation work well.

**Comment by ehuaa** [comment] 2023-10-20 02:32
> @ehuaa hi, could you try with the prebuilt docker image: `docker pull openmmlab/lmdeploy:latest`. https://hub.docker.com/r/openmmlab/lmdeploy/tags

@RunningLeon Can you give a tutorial of using docker file to compile lmdeploy from source and every time i modify some code, if i should reconstruct the docker file as well to compile it again?

**Comment by RunningLeon** [comment] 2023-10-23 00:29
@ehuaa hi, you could create a container and do everything inside it. Just like you do in a host machine.
```
docker pull openmmlab/lmdeploy:latest
docker run -it --rm --gpus=all openmmlab/lmdeploy:latest
...
```

**Comment by lvhan028** [comment] 2023-10-24 06:02
@ehuaa may check if PR #602 helps

**Comment by ehuaa** [comment] 2023-10-24 06:26
> @ehuaa hi, you could create a container and do everything inside it. Just like you do in a host machine.
> 
> ```
> docker pull openmmlab/lmdeploy:latest
> docker run -it --rm --gpus=all openmmlab/lmdeploy:latest
> ...
> ```

docker save my time, thanks

**Comment by ehuaa** [comment] 2023-10-24 06:26
> @ehuaa may check if PR #602 helps

Ok, I'll follow this instruction

**Comment by lvhan028** [comment] 2023-10-25 09:52
#602 has been merged. If there is any question, feel free to update this issue.

**Closed by lvhan028** 2023-10-25 09:52 UTC
Labels: Installation, awaiting response
