### ISSUE TITLE
[Bug] argparse.ArgumentError: argument command: conflicting subparser: chat

### ISSUE THREAD

**Issue by zcg-joker** [InternLM/lmdeploy#1396] opened 2024-04-04 16:35 UTC
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

运行控制台交互式对话命令lmdeploy chat /root/share/model_repos/internlm2-chat-7b  报错如下：
![image](https://github.com/InternLM/lmdeploy/assets/77949815/097fa552-2eb1-46be-83c8-af8b65233968)

### Reproduction

lmdeploy chat /root/share/model_repos/internlm2-chat-7b

### Environment

```Shell
终端运行lmdeploy check_env也报相同的错误
Traceback (most recent call last):
  File "/root/.conda/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/root/.conda/lib/python3.11/site-packages/lmdeploy/cli/entrypoint.py", line 19, in run
    CLI.add_parser_chat()
  File "/root/.conda/lib/python3.11/site-packages/lmdeploy/cli/cli.py", line 81, in add_parser_chat
    parser = CLI.subparsers.add_parser(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.conda/lib/python3.11/argparse.py", line 1192, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
argparse.ArgumentError: argument command: conflicting subparser: chat

lmdeploy版本为0.3.0
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "/root/.conda/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/root/.conda/lib/python3.11/site-packages/lmdeploy/cli/entrypoint.py", line 19, in run
    CLI.add_parser_chat()
  File "/root/.conda/lib/python3.11/site-packages/lmdeploy/cli/cli.py", line 81, in add_parser_chat
    parser = CLI.subparsers.add_parser(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.conda/lib/python3.11/argparse.py", line 1192, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
argparse.ArgumentError: argument command: conflicting subparser: chat
```

**Comment by zhulinJulia24** [comment] 2024-04-05 12:28
It seems occurs in python 3.11 version. If you are in a hurry, you can try it on python 3.10, it works fine on python 3.10.

**Comment by zcg-joker** [comment] 2024-04-05 12:31
> It seems occurs in python 3.11 version. If you are in a hurry, you can try it on python 3.10, it works fine on python 3.10.

Thank you, i will try it

**Comment by RunningLeon** [comment] 2024-04-07 02:13
Let me reproduce the issue and see if there's a good solution for py311.

**Comment by RunningLeon** [comment] 2024-04-07 04:05
@zcg-joker Hi, sorry for the trouble. If you have time, could try pr #1401.

**Comment by RunningLeon** [comment] 2024-04-15 07:46
> 大哥，是不是只修了chat没修serve啊

serve 不会有这个问题的。 你这边有问题的话，可以给下版本和复现代码

**Comment by lvhan028** [comment] 2024-04-22 11:26
closing it since no more activities. Feel free to reopen it if it is still an issue

**Closed by lvhan028** 2024-04-22 11:26 UTC
Labels: Bug:P1, awaiting response
